export function generateDocuments({ property, owner, tenant, agreedPrice, securityDeposit, startDate, endDate, duration, propertyType, category }) {
  
  const documents = [];
  const today = new Date().toLocaleDateString();
  
  // Common ID Proof document
  documents.push({
    type: 'id_proof',
    name: 'ID_Verification.pdf',
    content: generateIdProof(owner, tenant),
    generatedAt: new Date()
  });
  
  // Property specific documents
  if (category === 'pg') {
    documents.push({
      type: 'pg_rules',
      name: 'PG_Accommodation_Agreement.pdf',
      content: generatePGAgreement(property, owner, tenant, agreedPrice, securityDeposit, startDate, endDate),
      generatedAt: new Date()
    });
  } 
  else if (category === 'rent') {
    documents.push({
      type: 'agreement',
      name: 'Rent_Agreement.pdf',
      content: generateRentAgreement(property, owner, tenant, agreedPrice, securityDeposit, startDate, endDate, duration),
      generatedAt: new Date()
    });
    documents.push({
      type: 'stamp_paper',
      name: 'E_Stamp_Paper.pdf',
      content: generateStampPaper(property, owner, tenant, agreedPrice),
      generatedAt: new Date()
    });
  } 
  else if (category === 'sale') {
    documents.push({
      type: 'sale_deed',
      name: 'Sale_Deed.pdf',
      content: generateSaleDeed(property, owner, tenant, agreedPrice),
      generatedAt: new Date()
    });
  }
  
  return documents;
}

function generateIdProof(owner, tenant) {
  return `
========================================
         ID VERIFICATION DOCUMENT
========================================

Verified by MetroHome Finder
Date: ${new Date().toLocaleDateString()}

OWNER DETAILS:
- Name: ${owner.name}
- Email: ${owner.email}
- Phone: ${owner.phone}

TENANT DETAILS:
- Name: ${tenant.name}
- Email: ${tenant.email}
- Phone: ${tenant.phone}

Status: ✅ VERIFIED
========================================
  `;
}

function generateRentAgreement(property, owner, tenant, rent, deposit, startDate, endDate, duration) {
  return `
========================================
              RENT AGREEMENT
========================================

This Rent Agreement is made on ${new Date().toLocaleDateString()}

PARTIES:
LESSOR (Owner): ${owner.name}
LESSEE (Tenant): ${tenant.name}

PROPERTY DETAILS:
- Title: ${property.title}
- Location: ${property.location}
- Type: ${property.type}
- Bedrooms: ${property.bedrooms}
- Bathrooms: ${property.bathrooms}
- Area: ${property.areaSqft} sq.ft

FINANCIAL TERMS:
- Monthly Rent: ₹${rent.toLocaleString()}
- Security Deposit: ₹${deposit.toLocaleString()}

DURATION:
- Start Date: ${new Date(startDate).toLocaleDateString()}
- End Date: ${new Date(endDate).toLocaleDateString()}
- Duration: ${duration} months

TERMS & CONDITIONS:
1. Rent to be paid on or before 5th of every month
2. Security deposit refundable at time of vacating
3. 1 month notice period for termination
4. No subletting without owner's consent

========================================
This agreement is generated by MetroHome Finder
========================================
  `;
}

function generatePGAgreement(property, owner, tenant, rent, deposit, startDate, endDate) {
  return `
========================================
         PG ACCOMMODATION AGREEMENT
========================================

Agreement Date: ${new Date().toLocaleDateString()}

PARTIES:
OWNER: ${owner.name}
RESIDENT: ${tenant.name}

PG DETAILS:
- Property: ${property.title}
- Location: ${property.location}
- Room Type: ${property.bedrooms} Sharing

FEES STRUCTURE:
- Monthly Fee: ₹${rent.toLocaleString()}
- Security Deposit: ₹${deposit.toLocaleString()}
- Food Included: Yes (Breakfast + Dinner)
- WiFi Included: Yes

DURATION:
- Start Date: ${new Date(startDate).toLocaleDateString()}
- End Date: ${new Date(endDate).toLocaleDateString()}

PG RULES:
• Check-in: After 11:00 AM
• Check-out: Before 10:00 AM
• Visitors allowed: 9 AM - 9 PM
• No alcohol/smoking inside premises
• Quiet hours: 10 PM - 7 AM

========================================
Generated by MetroHome Finder
========================================
  `;
}

function generateSaleDeed(property, owner, buyer, price) {
  return `
========================================
                 SALE DEED
========================================

This Sale Deed is executed on ${new Date().toLocaleDateString()}

PARTIES:
SELLER: ${owner.name}
BUYER: ${buyer.name}

PROPERTY DETAILS:
- Title: ${property.title}
- Location: ${property.location}
- Area: ${property.areaSqft} sq.ft
- Type: ${property.type}

SALE CONSIDERATION:
- Total Sale Price: ₹${price.toLocaleString()}

PAYMENT TERMS:
- Booking Amount (10%): ₹${(price * 0.1).toLocaleString()}
- Registration (80%): ₹${(price * 0.8).toLocaleString()}
- Possession (10%): ₹${(price * 0.1).toLocaleString()}

========================================
This deed is generated by MetroHome Finder
========================================
  `;
}

function generateStampPaper(property, owner, tenant, amount) {
  const stampDuty = Math.floor((amount * 12) * 0.01);
  
  return `
========================================
            E-STAMP CERTIFICATE
========================================

Certificate No: ${Math.random().toString(36).substring(2, 15).toUpperCase()}
Date: ${new Date().toLocaleDateString()}

STAMP DUTY DETAILS:
- Property: ${property.title}
- Lessor: ${owner.name}
- Lessee: ${tenant.name}
- Monthly Rent: ₹${amount.toLocaleString()}
- Annual Rent: ₹${(amount * 12).toLocaleString()}
- Stamp Duty: ₹${stampDuty.toLocaleString()} (1% of annual rent)

This e-stamp paper is valid for the rent agreement.

========================================
  `;
}